### ISSUE TITLE
We need to make this package easier to find.

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome/native-package-installer#10]
https://www.reddit.com/r/ruby/comments/f3eb72/installing_msys2_packages_with_gem/

**Comment by kou** [comment]
Users should use `msys2_mingw_dependencies` gem metadata https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#user-content-msys2-library-dependency instead of this gem.

**Comment by kojix2** [comment]
I admit that I don't know much about this matter.
Added a link to the ubyinstaller article on reddit.
