### ISSUE TITLE
Build failure in msys2

### ISSUE THREAD

**Issue by Biswa96** [ruby-gnome/native-package-installer#13]
Ruby version: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]

Build failure in msys2 with this error:

```
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ rb_sysopen - ./NativePackageInstaller/Platform/ArchLinux/need_super_user_priviledge%3f-i.ri
```

The build recipe can be found [here](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-ruby-native-package-installer).

**Comment by kou** [comment]
Could you collect more logs with:

```diff
diff --git a/mingw-w64-ruby-native-package-installer/PKGBUILD b/mingw-w64-ruby-native-package-installer/PKGBUILD
index 9ec0aa750..f5cccb44b 100644
--- a/mingw-w64-ruby-native-package-installer/PKGBUILD
+++ b/mingw-w64-ruby-native-package-installer/PKGBUILD
@@ -20,7 +20,7 @@ package() {
   local _gemdir="$(ruby -e'puts Gem.default_dir')"
   _gemdir="$(cygpath -u ${_gemdir})"
   
-  ${MINGW_PREFIX}/bin/gem install --ignore-dependencies --no-user-install -i "${pkgdir}${_gemdir}" -n "${pkgdir}${MINGW_PREFIX}/bin" ${_gemname}-${pkgver}.gem
+  ${MINGW_PREFIX}/bin/gem install --ignore-dependencies --no-user-install -i "${pkgdir}${_gemdir}" -n "${pkgdir}${MINGW_PREFIX}/bin" --verbose --debug ${_gemname}-${pkgver}.gem
   
   rm "${pkgdir}${_gemdir}/cache/${_gemname}-${pkgver}.gem"  
 }
```

Workaround:

```diff
diff --git a/mingw-w64-ruby-native-package-installer/PKGBUILD b/mingw-w64-ruby-native-package-installer/PKGBUILD
index 9ec0aa750..ff49569eb 100644
--- a/mingw-w64-ruby-native-package-installer/PKGBUILD
+++ b/mingw-w64-ruby-native-package-installer/PKGBUILD
@@ -20,7 +20,7 @@ package() {
   local _gemdir="$(ruby -e'puts Gem.default_dir')"
   _gemdir="$(cygpath -u ${_gemdir})"
   
-  ${MINGW_PREFIX}/bin/gem install --ignore-dependencies --no-user-install -i "${pkgdir}${_gemdir}" -n "${pkgdir}${MINGW_PREFIX}/bin" ${_gemname}-${pkgver}.gem
+  ${MINGW_PREFIX}/bin/gem install --ignore-dependencies --no-user-install -i "${pkgdir}${_gemdir}" -n "${pkgdir}${MINGW_PREFIX}/bin" --no-document ${_gemname}-${pkgver}.gem
   
   rm "${pkgdir}${_gemdir}/cache/${_gemname}-${pkgver}.gem"  
 }
```

**Comment by Biswa96** [comment]
The verbose output is too long. Here is the text file with that output [verbose-output.txt](https://github.com/ruby-gnome/native-package-installer/files/7648163/verbose-output.txt). That workaround works. But it may be better without any workaround.

**Comment by Biswa96** [comment]
I think the script misidentifies msys2 as ArchLinux due to presence of pacman executable file.

**Comment by kou** [comment]
The error was occurred at https://github.com/ruby/ruby/blob/ruby_3_0/lib/rdoc/store.rb#L895 .

Could you try the following on the ucrt64 environment?

```ruby
require "fileutils"
FileUtils.mkdir_p("./NativePackageInstaller/Platform/ArchLinux")
File.open("./NativePackageInstaller/Platform/ArchLinux/need_super_
user_priviledge%3f-i.ri", "wb") {}
```

My guesses:

  1. `%` may be an invalid character on the environment.
  2. File name may be too long on the environment. (The current directory of the case will be `F:/my-MINGW-packages/mingw-w64-ruby-native-package-installer/pkg/mingw-w64-ucrt-x86_64-ruby-native-package-installer/ucrt64/lib/ruby/gems/3.0.0/gems/doc/native-package-installer-1.0.9/`)

> I think the script misidentifies msys2 as ArchLinux due to presence of pacman executable file.

This is not related. The error process id document generation. It doesn't run any code.

**Comment by Biswa96** [comment]
This works

```ruby
require "fileutils"
FileUtils.mkdir_p("./NativePackageInstaller/Platform/ArchLinux")
File.open("./NativePackageInstaller/Platform/ArchLinux/need_super_user_priviledge%3f-i.ri", "wb") {}
```

**Comment by kou** [comment]
OK. My guess 1. is rejected.

Did you run it at `F:/my-MINGW-packages/mingw-w64-ruby-native-package-installer/pkg/mingw-w64-ucrt-x86_64-ruby-native-package-installer/ucrt64/lib/ruby/gems/3.0.0/gems/doc/native-package-installer-1.0.9/`? So my guess 2. is also rejected.

BTW, is this occurred only with ucrt64? Or is this occurred with mingw64 too?

Can we reproduce this on local machine? Or do we need a specific environment such as hosted Windows machine for GitHub Actions?

**Comment by Biswa96** [comment]
> Did you run it at ...

If I run the ruby script in that path I get this error.

```
test.rb:7:in `initialize': No such file or directory @ rb_sysopen - ./NativePackageInstaller/Platform/ArchLinux/need_super_user_priviledge%3f-i.ri (Errno::ENOENT)
        from test.rb:7:in `open'
        from test.rb:7:in `<main>'
```

> Can we reproduce this on local machine?

I have not tested this with other build environments except ucrt64. I have just built ruby v3 in ucrt64. If you need packages to experiment with I can create a test pull request in msys2/mingw-packages repository. CI will create ruby v3 for all build environment including mingw64.

**Comment by Biswa96** [comment]
> File name may be too long on the environment. 

You were correct. The build succeed in CI which uses shorter path to build mingw packages. Feel free to close this issue.

**Comment by kou** [comment]
OK.
