### ISSUE TITLE
Installing gobject-introspection under Amazon Linux fails with "No such file or directory @ rb_sysopen - /etc/redhat-release"

### ISSUE THREAD

**Issue by docusend1** [ruby-gnome/native-package-installer#14]
I am trying to `gem install poppler` using AWS CodeBuild which runs a build environment based an Amazon Linux, which in turn is derived from RHEL/CentOS. Through a dependency chain this ends up trying to install gobject-introspection using native-package-installer which fails with the error below:

```
/codebuild/output/src977490374/src/vendor/bundle/ruby/2.6.0/gems/native-package-installer-1.1.3/lib/native-package-installer/platform/redhat.rb:46:in
`read': No such file or directory @ rb_sysopen - /etc/redhat-release
(Errno::ENOENT)
```

The code in `lib/native-package-installer/platform/redhat.rb` is trying to detect the OS version by inspecting the file `/etc/redhat-release`, however this file does not exist on Amazon Linux which instead has `/etc/system-release`. I have worked around this problem for now by copying system-release to redhat-release (I guess a symlink would work too):

`cp /etc/system-release /etc/redhat-release`

Obviously this is a bit if a hack, so perhaps there is a better way to detect the OS version? Maybe like this answer: [https://serverfault.com/questions/798427/what-linux-distribution-is-the-amazon-linux-ami-based-on#answer-1005265](https://serverfault.com/questions/798427/what-linux-distribution-is-the-amazon-linux-ami-based-on#answer-1005265)

**Comment by kou** [comment]
Could you try 1.1.4?

**Comment by docusend1** [comment]
Hi Kou,

Thanks for the quick turnaround. I've reverted my workaround and bumped the version to 1.1.4 and it works perfectly, thankyou!
